/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OnboardingStepRouteImport } from './routes/onboarding.$step'
import { Route as AuthenticatedMembreIndexRouteImport } from './routes/_authenticated.membre.index'
import { Route as AuthenticatedCoachIndexRouteImport } from './routes/_authenticated.coach.index'
import { Route as AuthenticatedMembreProgressionRouteImport } from './routes/_authenticated.membre.progression'
import { Route as AuthenticatedMembreProgrammeRouteImport } from './routes/_authenticated.membre.programme'
import { Route as AuthenticatedMembreProfilRouteImport } from './routes/_authenticated.membre.profil'
import { Route as AuthenticatedMembreLoggerRouteImport } from './routes/_authenticated.membre.logger'
import { Route as AuthenticatedMembreHistoriqueRouteImport } from './routes/_authenticated.membre.historique'
import { Route as AuthenticatedCoachRunningRouteImport } from './routes/_authenticated.coach.running'
import { Route as AuthenticatedCoachProgrammesRouteImport } from './routes/_authenticated.coach.programmes'
import { Route as AuthenticatedCoachMessagesRouteImport } from './routes/_authenticated.coach.messages'
import { Route as AuthenticatedCoachMembreRouteImport } from './routes/_authenticated.coach.membre'
import { Route as AuthenticatedCoachImportRouteImport } from './routes/_authenticated.coach.import'
import { Route as AuthenticatedCoachBuilderRouteImport } from './routes/_authenticated.coach.builder'
import { Route as AuthenticatedMembreSeanceSessionIdRouteImport } from './routes/_authenticated.membre.seance.$sessionId'
import { Route as AuthenticatedCoachProgrammesIdRouteImport } from './routes/_authenticated.coach.programmes.$id'
import { Route as AuthenticatedCoachMembreMemberIdRouteImport } from './routes/_authenticated.coach.membre.$memberId'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingStepRoute = OnboardingStepRouteImport.update({
  id: '/onboarding/$step',
  path: '/onboarding/$step',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedMembreIndexRoute =
  AuthenticatedMembreIndexRouteImport.update({
    id: '/membre/',
    path: '/membre/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCoachIndexRoute = AuthenticatedCoachIndexRouteImport.update({
  id: '/coach/',
  path: '/coach/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedMembreProgressionRoute =
  AuthenticatedMembreProgressionRouteImport.update({
    id: '/membre/progression',
    path: '/membre/progression',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedMembreProgrammeRoute =
  AuthenticatedMembreProgrammeRouteImport.update({
    id: '/membre/programme',
    path: '/membre/programme',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedMembreProfilRoute =
  AuthenticatedMembreProfilRouteImport.update({
    id: '/membre/profil',
    path: '/membre/profil',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedMembreLoggerRoute =
  AuthenticatedMembreLoggerRouteImport.update({
    id: '/membre/logger',
    path: '/membre/logger',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedMembreHistoriqueRoute =
  AuthenticatedMembreHistoriqueRouteImport.update({
    id: '/membre/historique',
    path: '/membre/historique',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCoachRunningRoute =
  AuthenticatedCoachRunningRouteImport.update({
    id: '/coach/running',
    path: '/coach/running',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCoachProgrammesRoute =
  AuthenticatedCoachProgrammesRouteImport.update({
    id: '/coach/programmes',
    path: '/coach/programmes',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCoachMessagesRoute =
  AuthenticatedCoachMessagesRouteImport.update({
    id: '/coach/messages',
    path: '/coach/messages',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCoachMembreRoute =
  AuthenticatedCoachMembreRouteImport.update({
    id: '/coach/membre',
    path: '/coach/membre',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCoachImportRoute =
  AuthenticatedCoachImportRouteImport.update({
    id: '/coach/import',
    path: '/coach/import',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCoachBuilderRoute =
  AuthenticatedCoachBuilderRouteImport.update({
    id: '/coach/builder',
    path: '/coach/builder',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedMembreSeanceSessionIdRoute =
  AuthenticatedMembreSeanceSessionIdRouteImport.update({
    id: '/membre/seance/$sessionId',
    path: '/membre/seance/$sessionId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCoachProgrammesIdRoute =
  AuthenticatedCoachProgrammesIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedCoachProgrammesRoute,
  } as any)
const AuthenticatedCoachMembreMemberIdRoute =
  AuthenticatedCoachMembreMemberIdRouteImport.update({
    id: '/$memberId',
    path: '/$memberId',
    getParentRoute: () => AuthenticatedCoachMembreRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/onboarding/$step': typeof OnboardingStepRoute
  '/coach/builder': typeof AuthenticatedCoachBuilderRoute
  '/coach/import': typeof AuthenticatedCoachImportRoute
  '/coach/membre': typeof AuthenticatedCoachMembreRouteWithChildren
  '/coach/messages': typeof AuthenticatedCoachMessagesRoute
  '/coach/programmes': typeof AuthenticatedCoachProgrammesRouteWithChildren
  '/coach/running': typeof AuthenticatedCoachRunningRoute
  '/membre/historique': typeof AuthenticatedMembreHistoriqueRoute
  '/membre/logger': typeof AuthenticatedMembreLoggerRoute
  '/membre/profil': typeof AuthenticatedMembreProfilRoute
  '/membre/programme': typeof AuthenticatedMembreProgrammeRoute
  '/membre/progression': typeof AuthenticatedMembreProgressionRoute
  '/coach/': typeof AuthenticatedCoachIndexRoute
  '/membre/': typeof AuthenticatedMembreIndexRoute
  '/coach/membre/$memberId': typeof AuthenticatedCoachMembreMemberIdRoute
  '/coach/programmes/$id': typeof AuthenticatedCoachProgrammesIdRoute
  '/membre/seance/$sessionId': typeof AuthenticatedMembreSeanceSessionIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/onboarding/$step': typeof OnboardingStepRoute
  '/coach/builder': typeof AuthenticatedCoachBuilderRoute
  '/coach/import': typeof AuthenticatedCoachImportRoute
  '/coach/membre': typeof AuthenticatedCoachMembreRouteWithChildren
  '/coach/messages': typeof AuthenticatedCoachMessagesRoute
  '/coach/programmes': typeof AuthenticatedCoachProgrammesRouteWithChildren
  '/coach/running': typeof AuthenticatedCoachRunningRoute
  '/membre/historique': typeof AuthenticatedMembreHistoriqueRoute
  '/membre/logger': typeof AuthenticatedMembreLoggerRoute
  '/membre/profil': typeof AuthenticatedMembreProfilRoute
  '/membre/programme': typeof AuthenticatedMembreProgrammeRoute
  '/membre/progression': typeof AuthenticatedMembreProgressionRoute
  '/coach': typeof AuthenticatedCoachIndexRoute
  '/membre': typeof AuthenticatedMembreIndexRoute
  '/coach/membre/$memberId': typeof AuthenticatedCoachMembreMemberIdRoute
  '/coach/programmes/$id': typeof AuthenticatedCoachProgrammesIdRoute
  '/membre/seance/$sessionId': typeof AuthenticatedMembreSeanceSessionIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/onboarding/$step': typeof OnboardingStepRoute
  '/_authenticated/coach/builder': typeof AuthenticatedCoachBuilderRoute
  '/_authenticated/coach/import': typeof AuthenticatedCoachImportRoute
  '/_authenticated/coach/membre': typeof AuthenticatedCoachMembreRouteWithChildren
  '/_authenticated/coach/messages': typeof AuthenticatedCoachMessagesRoute
  '/_authenticated/coach/programmes': typeof AuthenticatedCoachProgrammesRouteWithChildren
  '/_authenticated/coach/running': typeof AuthenticatedCoachRunningRoute
  '/_authenticated/membre/historique': typeof AuthenticatedMembreHistoriqueRoute
  '/_authenticated/membre/logger': typeof AuthenticatedMembreLoggerRoute
  '/_authenticated/membre/profil': typeof AuthenticatedMembreProfilRoute
  '/_authenticated/membre/programme': typeof AuthenticatedMembreProgrammeRoute
  '/_authenticated/membre/progression': typeof AuthenticatedMembreProgressionRoute
  '/_authenticated/coach/': typeof AuthenticatedCoachIndexRoute
  '/_authenticated/membre/': typeof AuthenticatedMembreIndexRoute
  '/_authenticated/coach/membre/$memberId': typeof AuthenticatedCoachMembreMemberIdRoute
  '/_authenticated/coach/programmes/$id': typeof AuthenticatedCoachProgrammesIdRoute
  '/_authenticated/membre/seance/$sessionId': typeof AuthenticatedMembreSeanceSessionIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/reset-password'
    | '/onboarding/$step'
    | '/coach/builder'
    | '/coach/import'
    | '/coach/membre'
    | '/coach/messages'
    | '/coach/programmes'
    | '/coach/running'
    | '/membre/historique'
    | '/membre/logger'
    | '/membre/profil'
    | '/membre/programme'
    | '/membre/progression'
    | '/coach/'
    | '/membre/'
    | '/coach/membre/$memberId'
    | '/coach/programmes/$id'
    | '/membre/seance/$sessionId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/reset-password'
    | '/onboarding/$step'
    | '/coach/builder'
    | '/coach/import'
    | '/coach/membre'
    | '/coach/messages'
    | '/coach/programmes'
    | '/coach/running'
    | '/membre/historique'
    | '/membre/logger'
    | '/membre/profil'
    | '/membre/programme'
    | '/membre/progression'
    | '/coach'
    | '/membre'
    | '/coach/membre/$memberId'
    | '/coach/programmes/$id'
    | '/membre/seance/$sessionId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/reset-password'
    | '/onboarding/$step'
    | '/_authenticated/coach/builder'
    | '/_authenticated/coach/import'
    | '/_authenticated/coach/membre'
    | '/_authenticated/coach/messages'
    | '/_authenticated/coach/programmes'
    | '/_authenticated/coach/running'
    | '/_authenticated/membre/historique'
    | '/_authenticated/membre/logger'
    | '/_authenticated/membre/profil'
    | '/_authenticated/membre/programme'
    | '/_authenticated/membre/progression'
    | '/_authenticated/coach/'
    | '/_authenticated/membre/'
    | '/_authenticated/coach/membre/$memberId'
    | '/_authenticated/coach/programmes/$id'
    | '/_authenticated/membre/seance/$sessionId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  OnboardingStepRoute: typeof OnboardingStepRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/$step': {
      id: '/onboarding/$step'
      path: '/onboarding/$step'
      fullPath: '/onboarding/$step'
      preLoaderRoute: typeof OnboardingStepRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/membre/': {
      id: '/_authenticated/membre/'
      path: '/membre'
      fullPath: '/membre/'
      preLoaderRoute: typeof AuthenticatedMembreIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/coach/': {
      id: '/_authenticated/coach/'
      path: '/coach'
      fullPath: '/coach/'
      preLoaderRoute: typeof AuthenticatedCoachIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/membre/progression': {
      id: '/_authenticated/membre/progression'
      path: '/membre/progression'
      fullPath: '/membre/progression'
      preLoaderRoute: typeof AuthenticatedMembreProgressionRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/membre/programme': {
      id: '/_authenticated/membre/programme'
      path: '/membre/programme'
      fullPath: '/membre/programme'
      preLoaderRoute: typeof AuthenticatedMembreProgrammeRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/membre/profil': {
      id: '/_authenticated/membre/profil'
      path: '/membre/profil'
      fullPath: '/membre/profil'
      preLoaderRoute: typeof AuthenticatedMembreProfilRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/membre/logger': {
      id: '/_authenticated/membre/logger'
      path: '/membre/logger'
      fullPath: '/membre/logger'
      preLoaderRoute: typeof AuthenticatedMembreLoggerRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/membre/historique': {
      id: '/_authenticated/membre/historique'
      path: '/membre/historique'
      fullPath: '/membre/historique'
      preLoaderRoute: typeof AuthenticatedMembreHistoriqueRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/coach/running': {
      id: '/_authenticated/coach/running'
      path: '/coach/running'
      fullPath: '/coach/running'
      preLoaderRoute: typeof AuthenticatedCoachRunningRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/coach/programmes': {
      id: '/_authenticated/coach/programmes'
      path: '/coach/programmes'
      fullPath: '/coach/programmes'
      preLoaderRoute: typeof AuthenticatedCoachProgrammesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/coach/messages': {
      id: '/_authenticated/coach/messages'
      path: '/coach/messages'
      fullPath: '/coach/messages'
      preLoaderRoute: typeof AuthenticatedCoachMessagesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/coach/membre': {
      id: '/_authenticated/coach/membre'
      path: '/coach/membre'
      fullPath: '/coach/membre'
      preLoaderRoute: typeof AuthenticatedCoachMembreRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/coach/import': {
      id: '/_authenticated/coach/import'
      path: '/coach/import'
      fullPath: '/coach/import'
      preLoaderRoute: typeof AuthenticatedCoachImportRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/coach/builder': {
      id: '/_authenticated/coach/builder'
      path: '/coach/builder'
      fullPath: '/coach/builder'
      preLoaderRoute: typeof AuthenticatedCoachBuilderRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/membre/seance/$sessionId': {
      id: '/_authenticated/membre/seance/$sessionId'
      path: '/membre/seance/$sessionId'
      fullPath: '/membre/seance/$sessionId'
      preLoaderRoute: typeof AuthenticatedMembreSeanceSessionIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/coach/programmes/$id': {
      id: '/_authenticated/coach/programmes/$id'
      path: '/$id'
      fullPath: '/coach/programmes/$id'
      preLoaderRoute: typeof AuthenticatedCoachProgrammesIdRouteImport
      parentRoute: typeof AuthenticatedCoachProgrammesRoute
    }
    '/_authenticated/coach/membre/$memberId': {
      id: '/_authenticated/coach/membre/$memberId'
      path: '/$memberId'
      fullPath: '/coach/membre/$memberId'
      preLoaderRoute: typeof AuthenticatedCoachMembreMemberIdRouteImport
      parentRoute: typeof AuthenticatedCoachMembreRoute
    }
  }
}

interface AuthenticatedCoachMembreRouteChildren {
  AuthenticatedCoachMembreMemberIdRoute: typeof AuthenticatedCoachMembreMemberIdRoute
}

const AuthenticatedCoachMembreRouteChildren: AuthenticatedCoachMembreRouteChildren =
  {
    AuthenticatedCoachMembreMemberIdRoute:
      AuthenticatedCoachMembreMemberIdRoute,
  }

const AuthenticatedCoachMembreRouteWithChildren =
  AuthenticatedCoachMembreRoute._addFileChildren(
    AuthenticatedCoachMembreRouteChildren,
  )

interface AuthenticatedCoachProgrammesRouteChildren {
  AuthenticatedCoachProgrammesIdRoute: typeof AuthenticatedCoachProgrammesIdRoute
}

const AuthenticatedCoachProgrammesRouteChildren: AuthenticatedCoachProgrammesRouteChildren =
  {
    AuthenticatedCoachProgrammesIdRoute: AuthenticatedCoachProgrammesIdRoute,
  }

const AuthenticatedCoachProgrammesRouteWithChildren =
  AuthenticatedCoachProgrammesRoute._addFileChildren(
    AuthenticatedCoachProgrammesRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedCoachBuilderRoute: typeof AuthenticatedCoachBuilderRoute
  AuthenticatedCoachImportRoute: typeof AuthenticatedCoachImportRoute
  AuthenticatedCoachMembreRoute: typeof AuthenticatedCoachMembreRouteWithChildren
  AuthenticatedCoachMessagesRoute: typeof AuthenticatedCoachMessagesRoute
  AuthenticatedCoachProgrammesRoute: typeof AuthenticatedCoachProgrammesRouteWithChildren
  AuthenticatedCoachRunningRoute: typeof AuthenticatedCoachRunningRoute
  AuthenticatedMembreHistoriqueRoute: typeof AuthenticatedMembreHistoriqueRoute
  AuthenticatedMembreLoggerRoute: typeof AuthenticatedMembreLoggerRoute
  AuthenticatedMembreProfilRoute: typeof AuthenticatedMembreProfilRoute
  AuthenticatedMembreProgrammeRoute: typeof AuthenticatedMembreProgrammeRoute
  AuthenticatedMembreProgressionRoute: typeof AuthenticatedMembreProgressionRoute
  AuthenticatedCoachIndexRoute: typeof AuthenticatedCoachIndexRoute
  AuthenticatedMembreIndexRoute: typeof AuthenticatedMembreIndexRoute
  AuthenticatedMembreSeanceSessionIdRoute: typeof AuthenticatedMembreSeanceSessionIdRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedCoachBuilderRoute: AuthenticatedCoachBuilderRoute,
  AuthenticatedCoachImportRoute: AuthenticatedCoachImportRoute,
  AuthenticatedCoachMembreRoute: AuthenticatedCoachMembreRouteWithChildren,
  AuthenticatedCoachMessagesRoute: AuthenticatedCoachMessagesRoute,
  AuthenticatedCoachProgrammesRoute:
    AuthenticatedCoachProgrammesRouteWithChildren,
  AuthenticatedCoachRunningRoute: AuthenticatedCoachRunningRoute,
  AuthenticatedMembreHistoriqueRoute: AuthenticatedMembreHistoriqueRoute,
  AuthenticatedMembreLoggerRoute: AuthenticatedMembreLoggerRoute,
  AuthenticatedMembreProfilRoute: AuthenticatedMembreProfilRoute,
  AuthenticatedMembreProgrammeRoute: AuthenticatedMembreProgrammeRoute,
  AuthenticatedMembreProgressionRoute: AuthenticatedMembreProgressionRoute,
  AuthenticatedCoachIndexRoute: AuthenticatedCoachIndexRoute,
  AuthenticatedMembreIndexRoute: AuthenticatedMembreIndexRoute,
  AuthenticatedMembreSeanceSessionIdRoute:
    AuthenticatedMembreSeanceSessionIdRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  OnboardingStepRoute: OnboardingStepRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
