/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OnboardingStepRouteImport } from './routes/onboarding.$step'
import { Route as AuthenticatedCoachRouteImport } from './routes/_authenticated.coach'
import { Route as AuthenticatedMembreIndexRouteImport } from './routes/_authenticated.membre.index'
import { Route as AuthenticatedCoachIndexRouteImport } from './routes/_authenticated.coach.index'
import { Route as AuthenticatedMembreProgressionRouteImport } from './routes/_authenticated.membre.progression'
import { Route as AuthenticatedMembreProgrammeRouteImport } from './routes/_authenticated.membre.programme'
import { Route as AuthenticatedMembreProfilRouteImport } from './routes/_authenticated.membre.profil'
import { Route as AuthenticatedMembrePlanningRouteImport } from './routes/_authenticated.membre.planning'
import { Route as AuthenticatedMembreMessagesRouteImport } from './routes/_authenticated.membre.messages'
import { Route as AuthenticatedMembreLoggerRouteImport } from './routes/_authenticated.membre.logger'
import { Route as AuthenticatedMembreHistoriqueRouteImport } from './routes/_authenticated.membre.historique'
import { Route as AuthenticatedMembreCommencerRouteImport } from './routes/_authenticated.membre.commencer'
import { Route as AuthenticatedMembreCarnetRouteImport } from './routes/_authenticated.membre.carnet'
import { Route as AuthenticatedCoachRunningRouteImport } from './routes/_authenticated.coach.running'
import { Route as AuthenticatedCoachProgrammesRouteImport } from './routes/_authenticated.coach.programmes'
import { Route as AuthenticatedCoachMessagesRouteImport } from './routes/_authenticated.coach.messages'
import { Route as AuthenticatedCoachInvitationsRouteImport } from './routes/_authenticated.coach.invitations'
import { Route as AuthenticatedCoachImportRouteImport } from './routes/_authenticated.coach.import'
import { Route as AuthenticatedCoachExercicesRouteImport } from './routes/_authenticated.coach.exercices'
import { Route as AuthenticatedCoachBuilderRouteImport } from './routes/_authenticated.coach.builder'
import { Route as LovableEmailQueueProcessRouteImport } from './routes/lovable/email/queue/process'
import { Route as LovableEmailAuthWebhookRouteImport } from './routes/lovable/email/auth/webhook'
import { Route as LovableEmailAuthPreviewRouteImport } from './routes/lovable/email/auth/preview'
import { Route as ApiPublicHooksGenerateLogbooksRouteImport } from './routes/api/public/hooks/generate-logbooks'
import { Route as AuthenticatedMembreSeanceSessionIdRouteImport } from './routes/_authenticated.membre.seance.$sessionId'
import { Route as AuthenticatedMembreSeanceLibreSessionIdRouteImport } from './routes/_authenticated.membre.seance-libre.$sessionId'
import { Route as AuthenticatedMembreCarnetWeekRouteImport } from './routes/_authenticated.membre.carnet.$week'
import { Route as AuthenticatedCoachSeanceSessionIdRouteImport } from './routes/_authenticated.coach.seance.$sessionId'
import { Route as AuthenticatedCoachProgrammesIdRouteImport } from './routes/_authenticated.coach.programmes.$id'
import { Route as AuthenticatedCoachMembreMemberIdRouteImport } from './routes/_authenticated.coach.membre.$memberId'
import { Route as AuthenticatedCoachBuilderIdRouteImport } from './routes/_authenticated.coach.builder.$id'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingStepRoute = OnboardingStepRouteImport.update({
  id: '/onboarding/$step',
  path: '/onboarding/$step',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedCoachRoute = AuthenticatedCoachRouteImport.update({
  id: '/coach',
  path: '/coach',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedMembreIndexRoute =
  AuthenticatedMembreIndexRouteImport.update({
    id: '/membre/',
    path: '/membre/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCoachIndexRoute = AuthenticatedCoachIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedCoachRoute,
} as any)
const AuthenticatedMembreProgressionRoute =
  AuthenticatedMembreProgressionRouteImport.update({
    id: '/membre/progression',
    path: '/membre/progression',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedMembreProgrammeRoute =
  AuthenticatedMembreProgrammeRouteImport.update({
    id: '/membre/programme',
    path: '/membre/programme',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedMembreProfilRoute =
  AuthenticatedMembreProfilRouteImport.update({
    id: '/membre/profil',
    path: '/membre/profil',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedMembrePlanningRoute =
  AuthenticatedMembrePlanningRouteImport.update({
    id: '/membre/planning',
    path: '/membre/planning',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedMembreMessagesRoute =
  AuthenticatedMembreMessagesRouteImport.update({
    id: '/membre/messages',
    path: '/membre/messages',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedMembreLoggerRoute =
  AuthenticatedMembreLoggerRouteImport.update({
    id: '/membre/logger',
    path: '/membre/logger',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedMembreHistoriqueRoute =
  AuthenticatedMembreHistoriqueRouteImport.update({
    id: '/membre/historique',
    path: '/membre/historique',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedMembreCommencerRoute =
  AuthenticatedMembreCommencerRouteImport.update({
    id: '/membre/commencer',
    path: '/membre/commencer',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedMembreCarnetRoute =
  AuthenticatedMembreCarnetRouteImport.update({
    id: '/membre/carnet',
    path: '/membre/carnet',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCoachRunningRoute =
  AuthenticatedCoachRunningRouteImport.update({
    id: '/running',
    path: '/running',
    getParentRoute: () => AuthenticatedCoachRoute,
  } as any)
const AuthenticatedCoachProgrammesRoute =
  AuthenticatedCoachProgrammesRouteImport.update({
    id: '/programmes',
    path: '/programmes',
    getParentRoute: () => AuthenticatedCoachRoute,
  } as any)
const AuthenticatedCoachMessagesRoute =
  AuthenticatedCoachMessagesRouteImport.update({
    id: '/messages',
    path: '/messages',
    getParentRoute: () => AuthenticatedCoachRoute,
  } as any)
const AuthenticatedCoachInvitationsRoute =
  AuthenticatedCoachInvitationsRouteImport.update({
    id: '/invitations',
    path: '/invitations',
    getParentRoute: () => AuthenticatedCoachRoute,
  } as any)
const AuthenticatedCoachImportRoute =
  AuthenticatedCoachImportRouteImport.update({
    id: '/import',
    path: '/import',
    getParentRoute: () => AuthenticatedCoachRoute,
  } as any)
const AuthenticatedCoachExercicesRoute =
  AuthenticatedCoachExercicesRouteImport.update({
    id: '/exercices',
    path: '/exercices',
    getParentRoute: () => AuthenticatedCoachRoute,
  } as any)
const AuthenticatedCoachBuilderRoute =
  AuthenticatedCoachBuilderRouteImport.update({
    id: '/builder',
    path: '/builder',
    getParentRoute: () => AuthenticatedCoachRoute,
  } as any)
const LovableEmailQueueProcessRoute =
  LovableEmailQueueProcessRouteImport.update({
    id: '/lovable/email/queue/process',
    path: '/lovable/email/queue/process',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailAuthWebhookRoute = LovableEmailAuthWebhookRouteImport.update({
  id: '/lovable/email/auth/webhook',
  path: '/lovable/email/auth/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailAuthPreviewRoute = LovableEmailAuthPreviewRouteImport.update({
  id: '/lovable/email/auth/preview',
  path: '/lovable/email/auth/preview',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksGenerateLogbooksRoute =
  ApiPublicHooksGenerateLogbooksRouteImport.update({
    id: '/api/public/hooks/generate-logbooks',
    path: '/api/public/hooks/generate-logbooks',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedMembreSeanceSessionIdRoute =
  AuthenticatedMembreSeanceSessionIdRouteImport.update({
    id: '/membre/seance/$sessionId',
    path: '/membre/seance/$sessionId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedMembreSeanceLibreSessionIdRoute =
  AuthenticatedMembreSeanceLibreSessionIdRouteImport.update({
    id: '/membre/seance-libre/$sessionId',
    path: '/membre/seance-libre/$sessionId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedMembreCarnetWeekRoute =
  AuthenticatedMembreCarnetWeekRouteImport.update({
    id: '/$week',
    path: '/$week',
    getParentRoute: () => AuthenticatedMembreCarnetRoute,
  } as any)
const AuthenticatedCoachSeanceSessionIdRoute =
  AuthenticatedCoachSeanceSessionIdRouteImport.update({
    id: '/seance/$sessionId',
    path: '/seance/$sessionId',
    getParentRoute: () => AuthenticatedCoachRoute,
  } as any)
const AuthenticatedCoachProgrammesIdRoute =
  AuthenticatedCoachProgrammesIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedCoachProgrammesRoute,
  } as any)
const AuthenticatedCoachMembreMemberIdRoute =
  AuthenticatedCoachMembreMemberIdRouteImport.update({
    id: '/membre/$memberId',
    path: '/membre/$memberId',
    getParentRoute: () => AuthenticatedCoachRoute,
  } as any)
const AuthenticatedCoachBuilderIdRoute =
  AuthenticatedCoachBuilderIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedCoachBuilderRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/coach': typeof AuthenticatedCoachRouteWithChildren
  '/onboarding/$step': typeof OnboardingStepRoute
  '/coach/builder': typeof AuthenticatedCoachBuilderRouteWithChildren
  '/coach/exercices': typeof AuthenticatedCoachExercicesRoute
  '/coach/import': typeof AuthenticatedCoachImportRoute
  '/coach/invitations': typeof AuthenticatedCoachInvitationsRoute
  '/coach/messages': typeof AuthenticatedCoachMessagesRoute
  '/coach/programmes': typeof AuthenticatedCoachProgrammesRouteWithChildren
  '/coach/running': typeof AuthenticatedCoachRunningRoute
  '/membre/carnet': typeof AuthenticatedMembreCarnetRouteWithChildren
  '/membre/commencer': typeof AuthenticatedMembreCommencerRoute
  '/membre/historique': typeof AuthenticatedMembreHistoriqueRoute
  '/membre/logger': typeof AuthenticatedMembreLoggerRoute
  '/membre/messages': typeof AuthenticatedMembreMessagesRoute
  '/membre/planning': typeof AuthenticatedMembrePlanningRoute
  '/membre/profil': typeof AuthenticatedMembreProfilRoute
  '/membre/programme': typeof AuthenticatedMembreProgrammeRoute
  '/membre/progression': typeof AuthenticatedMembreProgressionRoute
  '/coach/': typeof AuthenticatedCoachIndexRoute
  '/membre/': typeof AuthenticatedMembreIndexRoute
  '/coach/builder/$id': typeof AuthenticatedCoachBuilderIdRoute
  '/coach/membre/$memberId': typeof AuthenticatedCoachMembreMemberIdRoute
  '/coach/programmes/$id': typeof AuthenticatedCoachProgrammesIdRoute
  '/coach/seance/$sessionId': typeof AuthenticatedCoachSeanceSessionIdRoute
  '/membre/carnet/$week': typeof AuthenticatedMembreCarnetWeekRoute
  '/membre/seance-libre/$sessionId': typeof AuthenticatedMembreSeanceLibreSessionIdRoute
  '/membre/seance/$sessionId': typeof AuthenticatedMembreSeanceSessionIdRoute
  '/api/public/hooks/generate-logbooks': typeof ApiPublicHooksGenerateLogbooksRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/onboarding/$step': typeof OnboardingStepRoute
  '/coach/builder': typeof AuthenticatedCoachBuilderRouteWithChildren
  '/coach/exercices': typeof AuthenticatedCoachExercicesRoute
  '/coach/import': typeof AuthenticatedCoachImportRoute
  '/coach/invitations': typeof AuthenticatedCoachInvitationsRoute
  '/coach/messages': typeof AuthenticatedCoachMessagesRoute
  '/coach/programmes': typeof AuthenticatedCoachProgrammesRouteWithChildren
  '/coach/running': typeof AuthenticatedCoachRunningRoute
  '/membre/carnet': typeof AuthenticatedMembreCarnetRouteWithChildren
  '/membre/commencer': typeof AuthenticatedMembreCommencerRoute
  '/membre/historique': typeof AuthenticatedMembreHistoriqueRoute
  '/membre/logger': typeof AuthenticatedMembreLoggerRoute
  '/membre/messages': typeof AuthenticatedMembreMessagesRoute
  '/membre/planning': typeof AuthenticatedMembrePlanningRoute
  '/membre/profil': typeof AuthenticatedMembreProfilRoute
  '/membre/programme': typeof AuthenticatedMembreProgrammeRoute
  '/membre/progression': typeof AuthenticatedMembreProgressionRoute
  '/coach': typeof AuthenticatedCoachIndexRoute
  '/membre': typeof AuthenticatedMembreIndexRoute
  '/coach/builder/$id': typeof AuthenticatedCoachBuilderIdRoute
  '/coach/membre/$memberId': typeof AuthenticatedCoachMembreMemberIdRoute
  '/coach/programmes/$id': typeof AuthenticatedCoachProgrammesIdRoute
  '/coach/seance/$sessionId': typeof AuthenticatedCoachSeanceSessionIdRoute
  '/membre/carnet/$week': typeof AuthenticatedMembreCarnetWeekRoute
  '/membre/seance-libre/$sessionId': typeof AuthenticatedMembreSeanceLibreSessionIdRoute
  '/membre/seance/$sessionId': typeof AuthenticatedMembreSeanceSessionIdRoute
  '/api/public/hooks/generate-logbooks': typeof ApiPublicHooksGenerateLogbooksRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/_authenticated/coach': typeof AuthenticatedCoachRouteWithChildren
  '/onboarding/$step': typeof OnboardingStepRoute
  '/_authenticated/coach/builder': typeof AuthenticatedCoachBuilderRouteWithChildren
  '/_authenticated/coach/exercices': typeof AuthenticatedCoachExercicesRoute
  '/_authenticated/coach/import': typeof AuthenticatedCoachImportRoute
  '/_authenticated/coach/invitations': typeof AuthenticatedCoachInvitationsRoute
  '/_authenticated/coach/messages': typeof AuthenticatedCoachMessagesRoute
  '/_authenticated/coach/programmes': typeof AuthenticatedCoachProgrammesRouteWithChildren
  '/_authenticated/coach/running': typeof AuthenticatedCoachRunningRoute
  '/_authenticated/membre/carnet': typeof AuthenticatedMembreCarnetRouteWithChildren
  '/_authenticated/membre/commencer': typeof AuthenticatedMembreCommencerRoute
  '/_authenticated/membre/historique': typeof AuthenticatedMembreHistoriqueRoute
  '/_authenticated/membre/logger': typeof AuthenticatedMembreLoggerRoute
  '/_authenticated/membre/messages': typeof AuthenticatedMembreMessagesRoute
  '/_authenticated/membre/planning': typeof AuthenticatedMembrePlanningRoute
  '/_authenticated/membre/profil': typeof AuthenticatedMembreProfilRoute
  '/_authenticated/membre/programme': typeof AuthenticatedMembreProgrammeRoute
  '/_authenticated/membre/progression': typeof AuthenticatedMembreProgressionRoute
  '/_authenticated/coach/': typeof AuthenticatedCoachIndexRoute
  '/_authenticated/membre/': typeof AuthenticatedMembreIndexRoute
  '/_authenticated/coach/builder/$id': typeof AuthenticatedCoachBuilderIdRoute
  '/_authenticated/coach/membre/$memberId': typeof AuthenticatedCoachMembreMemberIdRoute
  '/_authenticated/coach/programmes/$id': typeof AuthenticatedCoachProgrammesIdRoute
  '/_authenticated/coach/seance/$sessionId': typeof AuthenticatedCoachSeanceSessionIdRoute
  '/_authenticated/membre/carnet/$week': typeof AuthenticatedMembreCarnetWeekRoute
  '/_authenticated/membre/seance-libre/$sessionId': typeof AuthenticatedMembreSeanceLibreSessionIdRoute
  '/_authenticated/membre/seance/$sessionId': typeof AuthenticatedMembreSeanceSessionIdRoute
  '/api/public/hooks/generate-logbooks': typeof ApiPublicHooksGenerateLogbooksRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/coach'
    | '/onboarding/$step'
    | '/coach/builder'
    | '/coach/exercices'
    | '/coach/import'
    | '/coach/invitations'
    | '/coach/messages'
    | '/coach/programmes'
    | '/coach/running'
    | '/membre/carnet'
    | '/membre/commencer'
    | '/membre/historique'
    | '/membre/logger'
    | '/membre/messages'
    | '/membre/planning'
    | '/membre/profil'
    | '/membre/programme'
    | '/membre/progression'
    | '/coach/'
    | '/membre/'
    | '/coach/builder/$id'
    | '/coach/membre/$memberId'
    | '/coach/programmes/$id'
    | '/coach/seance/$sessionId'
    | '/membre/carnet/$week'
    | '/membre/seance-libre/$sessionId'
    | '/membre/seance/$sessionId'
    | '/api/public/hooks/generate-logbooks'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/onboarding/$step'
    | '/coach/builder'
    | '/coach/exercices'
    | '/coach/import'
    | '/coach/invitations'
    | '/coach/messages'
    | '/coach/programmes'
    | '/coach/running'
    | '/membre/carnet'
    | '/membre/commencer'
    | '/membre/historique'
    | '/membre/logger'
    | '/membre/messages'
    | '/membre/planning'
    | '/membre/profil'
    | '/membre/programme'
    | '/membre/progression'
    | '/coach'
    | '/membre'
    | '/coach/builder/$id'
    | '/coach/membre/$memberId'
    | '/coach/programmes/$id'
    | '/coach/seance/$sessionId'
    | '/membre/carnet/$week'
    | '/membre/seance-libre/$sessionId'
    | '/membre/seance/$sessionId'
    | '/api/public/hooks/generate-logbooks'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/_authenticated/coach'
    | '/onboarding/$step'
    | '/_authenticated/coach/builder'
    | '/_authenticated/coach/exercices'
    | '/_authenticated/coach/import'
    | '/_authenticated/coach/invitations'
    | '/_authenticated/coach/messages'
    | '/_authenticated/coach/programmes'
    | '/_authenticated/coach/running'
    | '/_authenticated/membre/carnet'
    | '/_authenticated/membre/commencer'
    | '/_authenticated/membre/historique'
    | '/_authenticated/membre/logger'
    | '/_authenticated/membre/messages'
    | '/_authenticated/membre/planning'
    | '/_authenticated/membre/profil'
    | '/_authenticated/membre/programme'
    | '/_authenticated/membre/progression'
    | '/_authenticated/coach/'
    | '/_authenticated/membre/'
    | '/_authenticated/coach/builder/$id'
    | '/_authenticated/coach/membre/$memberId'
    | '/_authenticated/coach/programmes/$id'
    | '/_authenticated/coach/seance/$sessionId'
    | '/_authenticated/membre/carnet/$week'
    | '/_authenticated/membre/seance-libre/$sessionId'
    | '/_authenticated/membre/seance/$sessionId'
    | '/api/public/hooks/generate-logbooks'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
  OnboardingStepRoute: typeof OnboardingStepRoute
  ApiPublicHooksGenerateLogbooksRoute: typeof ApiPublicHooksGenerateLogbooksRoute
  LovableEmailAuthPreviewRoute: typeof LovableEmailAuthPreviewRoute
  LovableEmailAuthWebhookRoute: typeof LovableEmailAuthWebhookRoute
  LovableEmailQueueProcessRoute: typeof LovableEmailQueueProcessRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/$step': {
      id: '/onboarding/$step'
      path: '/onboarding/$step'
      fullPath: '/onboarding/$step'
      preLoaderRoute: typeof OnboardingStepRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/coach': {
      id: '/_authenticated/coach'
      path: '/coach'
      fullPath: '/coach'
      preLoaderRoute: typeof AuthenticatedCoachRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/membre/': {
      id: '/_authenticated/membre/'
      path: '/membre'
      fullPath: '/membre/'
      preLoaderRoute: typeof AuthenticatedMembreIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/coach/': {
      id: '/_authenticated/coach/'
      path: '/'
      fullPath: '/coach/'
      preLoaderRoute: typeof AuthenticatedCoachIndexRouteImport
      parentRoute: typeof AuthenticatedCoachRoute
    }
    '/_authenticated/membre/progression': {
      id: '/_authenticated/membre/progression'
      path: '/membre/progression'
      fullPath: '/membre/progression'
      preLoaderRoute: typeof AuthenticatedMembreProgressionRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/membre/programme': {
      id: '/_authenticated/membre/programme'
      path: '/membre/programme'
      fullPath: '/membre/programme'
      preLoaderRoute: typeof AuthenticatedMembreProgrammeRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/membre/profil': {
      id: '/_authenticated/membre/profil'
      path: '/membre/profil'
      fullPath: '/membre/profil'
      preLoaderRoute: typeof AuthenticatedMembreProfilRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/membre/planning': {
      id: '/_authenticated/membre/planning'
      path: '/membre/planning'
      fullPath: '/membre/planning'
      preLoaderRoute: typeof AuthenticatedMembrePlanningRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/membre/messages': {
      id: '/_authenticated/membre/messages'
      path: '/membre/messages'
      fullPath: '/membre/messages'
      preLoaderRoute: typeof AuthenticatedMembreMessagesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/membre/logger': {
      id: '/_authenticated/membre/logger'
      path: '/membre/logger'
      fullPath: '/membre/logger'
      preLoaderRoute: typeof AuthenticatedMembreLoggerRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/membre/historique': {
      id: '/_authenticated/membre/historique'
      path: '/membre/historique'
      fullPath: '/membre/historique'
      preLoaderRoute: typeof AuthenticatedMembreHistoriqueRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/membre/commencer': {
      id: '/_authenticated/membre/commencer'
      path: '/membre/commencer'
      fullPath: '/membre/commencer'
      preLoaderRoute: typeof AuthenticatedMembreCommencerRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/membre/carnet': {
      id: '/_authenticated/membre/carnet'
      path: '/membre/carnet'
      fullPath: '/membre/carnet'
      preLoaderRoute: typeof AuthenticatedMembreCarnetRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/coach/running': {
      id: '/_authenticated/coach/running'
      path: '/running'
      fullPath: '/coach/running'
      preLoaderRoute: typeof AuthenticatedCoachRunningRouteImport
      parentRoute: typeof AuthenticatedCoachRoute
    }
    '/_authenticated/coach/programmes': {
      id: '/_authenticated/coach/programmes'
      path: '/programmes'
      fullPath: '/coach/programmes'
      preLoaderRoute: typeof AuthenticatedCoachProgrammesRouteImport
      parentRoute: typeof AuthenticatedCoachRoute
    }
    '/_authenticated/coach/messages': {
      id: '/_authenticated/coach/messages'
      path: '/messages'
      fullPath: '/coach/messages'
      preLoaderRoute: typeof AuthenticatedCoachMessagesRouteImport
      parentRoute: typeof AuthenticatedCoachRoute
    }
    '/_authenticated/coach/invitations': {
      id: '/_authenticated/coach/invitations'
      path: '/invitations'
      fullPath: '/coach/invitations'
      preLoaderRoute: typeof AuthenticatedCoachInvitationsRouteImport
      parentRoute: typeof AuthenticatedCoachRoute
    }
    '/_authenticated/coach/import': {
      id: '/_authenticated/coach/import'
      path: '/import'
      fullPath: '/coach/import'
      preLoaderRoute: typeof AuthenticatedCoachImportRouteImport
      parentRoute: typeof AuthenticatedCoachRoute
    }
    '/_authenticated/coach/exercices': {
      id: '/_authenticated/coach/exercices'
      path: '/exercices'
      fullPath: '/coach/exercices'
      preLoaderRoute: typeof AuthenticatedCoachExercicesRouteImport
      parentRoute: typeof AuthenticatedCoachRoute
    }
    '/_authenticated/coach/builder': {
      id: '/_authenticated/coach/builder'
      path: '/builder'
      fullPath: '/coach/builder'
      preLoaderRoute: typeof AuthenticatedCoachBuilderRouteImport
      parentRoute: typeof AuthenticatedCoachRoute
    }
    '/lovable/email/queue/process': {
      id: '/lovable/email/queue/process'
      path: '/lovable/email/queue/process'
      fullPath: '/lovable/email/queue/process'
      preLoaderRoute: typeof LovableEmailQueueProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/webhook': {
      id: '/lovable/email/auth/webhook'
      path: '/lovable/email/auth/webhook'
      fullPath: '/lovable/email/auth/webhook'
      preLoaderRoute: typeof LovableEmailAuthWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/preview': {
      id: '/lovable/email/auth/preview'
      path: '/lovable/email/auth/preview'
      fullPath: '/lovable/email/auth/preview'
      preLoaderRoute: typeof LovableEmailAuthPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/generate-logbooks': {
      id: '/api/public/hooks/generate-logbooks'
      path: '/api/public/hooks/generate-logbooks'
      fullPath: '/api/public/hooks/generate-logbooks'
      preLoaderRoute: typeof ApiPublicHooksGenerateLogbooksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/membre/seance/$sessionId': {
      id: '/_authenticated/membre/seance/$sessionId'
      path: '/membre/seance/$sessionId'
      fullPath: '/membre/seance/$sessionId'
      preLoaderRoute: typeof AuthenticatedMembreSeanceSessionIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/membre/seance-libre/$sessionId': {
      id: '/_authenticated/membre/seance-libre/$sessionId'
      path: '/membre/seance-libre/$sessionId'
      fullPath: '/membre/seance-libre/$sessionId'
      preLoaderRoute: typeof AuthenticatedMembreSeanceLibreSessionIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/membre/carnet/$week': {
      id: '/_authenticated/membre/carnet/$week'
      path: '/$week'
      fullPath: '/membre/carnet/$week'
      preLoaderRoute: typeof AuthenticatedMembreCarnetWeekRouteImport
      parentRoute: typeof AuthenticatedMembreCarnetRoute
    }
    '/_authenticated/coach/seance/$sessionId': {
      id: '/_authenticated/coach/seance/$sessionId'
      path: '/seance/$sessionId'
      fullPath: '/coach/seance/$sessionId'
      preLoaderRoute: typeof AuthenticatedCoachSeanceSessionIdRouteImport
      parentRoute: typeof AuthenticatedCoachRoute
    }
    '/_authenticated/coach/programmes/$id': {
      id: '/_authenticated/coach/programmes/$id'
      path: '/$id'
      fullPath: '/coach/programmes/$id'
      preLoaderRoute: typeof AuthenticatedCoachProgrammesIdRouteImport
      parentRoute: typeof AuthenticatedCoachProgrammesRoute
    }
    '/_authenticated/coach/membre/$memberId': {
      id: '/_authenticated/coach/membre/$memberId'
      path: '/membre/$memberId'
      fullPath: '/coach/membre/$memberId'
      preLoaderRoute: typeof AuthenticatedCoachMembreMemberIdRouteImport
      parentRoute: typeof AuthenticatedCoachRoute
    }
    '/_authenticated/coach/builder/$id': {
      id: '/_authenticated/coach/builder/$id'
      path: '/$id'
      fullPath: '/coach/builder/$id'
      preLoaderRoute: typeof AuthenticatedCoachBuilderIdRouteImport
      parentRoute: typeof AuthenticatedCoachBuilderRoute
    }
  }
}

interface AuthenticatedCoachBuilderRouteChildren {
  AuthenticatedCoachBuilderIdRoute: typeof AuthenticatedCoachBuilderIdRoute
}

const AuthenticatedCoachBuilderRouteChildren: AuthenticatedCoachBuilderRouteChildren =
  {
    AuthenticatedCoachBuilderIdRoute: AuthenticatedCoachBuilderIdRoute,
  }

const AuthenticatedCoachBuilderRouteWithChildren =
  AuthenticatedCoachBuilderRoute._addFileChildren(
    AuthenticatedCoachBuilderRouteChildren,
  )

interface AuthenticatedCoachProgrammesRouteChildren {
  AuthenticatedCoachProgrammesIdRoute: typeof AuthenticatedCoachProgrammesIdRoute
}

const AuthenticatedCoachProgrammesRouteChildren: AuthenticatedCoachProgrammesRouteChildren =
  {
    AuthenticatedCoachProgrammesIdRoute: AuthenticatedCoachProgrammesIdRoute,
  }

const AuthenticatedCoachProgrammesRouteWithChildren =
  AuthenticatedCoachProgrammesRoute._addFileChildren(
    AuthenticatedCoachProgrammesRouteChildren,
  )

interface AuthenticatedCoachRouteChildren {
  AuthenticatedCoachBuilderRoute: typeof AuthenticatedCoachBuilderRouteWithChildren
  AuthenticatedCoachExercicesRoute: typeof AuthenticatedCoachExercicesRoute
  AuthenticatedCoachImportRoute: typeof AuthenticatedCoachImportRoute
  AuthenticatedCoachInvitationsRoute: typeof AuthenticatedCoachInvitationsRoute
  AuthenticatedCoachMessagesRoute: typeof AuthenticatedCoachMessagesRoute
  AuthenticatedCoachProgrammesRoute: typeof AuthenticatedCoachProgrammesRouteWithChildren
  AuthenticatedCoachRunningRoute: typeof AuthenticatedCoachRunningRoute
  AuthenticatedCoachIndexRoute: typeof AuthenticatedCoachIndexRoute
  AuthenticatedCoachMembreMemberIdRoute: typeof AuthenticatedCoachMembreMemberIdRoute
  AuthenticatedCoachSeanceSessionIdRoute: typeof AuthenticatedCoachSeanceSessionIdRoute
}

const AuthenticatedCoachRouteChildren: AuthenticatedCoachRouteChildren = {
  AuthenticatedCoachBuilderRoute: AuthenticatedCoachBuilderRouteWithChildren,
  AuthenticatedCoachExercicesRoute: AuthenticatedCoachExercicesRoute,
  AuthenticatedCoachImportRoute: AuthenticatedCoachImportRoute,
  AuthenticatedCoachInvitationsRoute: AuthenticatedCoachInvitationsRoute,
  AuthenticatedCoachMessagesRoute: AuthenticatedCoachMessagesRoute,
  AuthenticatedCoachProgrammesRoute:
    AuthenticatedCoachProgrammesRouteWithChildren,
  AuthenticatedCoachRunningRoute: AuthenticatedCoachRunningRoute,
  AuthenticatedCoachIndexRoute: AuthenticatedCoachIndexRoute,
  AuthenticatedCoachMembreMemberIdRoute: AuthenticatedCoachMembreMemberIdRoute,
  AuthenticatedCoachSeanceSessionIdRoute:
    AuthenticatedCoachSeanceSessionIdRoute,
}

const AuthenticatedCoachRouteWithChildren =
  AuthenticatedCoachRoute._addFileChildren(AuthenticatedCoachRouteChildren)

interface AuthenticatedMembreCarnetRouteChildren {
  AuthenticatedMembreCarnetWeekRoute: typeof AuthenticatedMembreCarnetWeekRoute
}

const AuthenticatedMembreCarnetRouteChildren: AuthenticatedMembreCarnetRouteChildren =
  {
    AuthenticatedMembreCarnetWeekRoute: AuthenticatedMembreCarnetWeekRoute,
  }

const AuthenticatedMembreCarnetRouteWithChildren =
  AuthenticatedMembreCarnetRoute._addFileChildren(
    AuthenticatedMembreCarnetRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedCoachRoute: typeof AuthenticatedCoachRouteWithChildren
  AuthenticatedMembreCarnetRoute: typeof AuthenticatedMembreCarnetRouteWithChildren
  AuthenticatedMembreCommencerRoute: typeof AuthenticatedMembreCommencerRoute
  AuthenticatedMembreHistoriqueRoute: typeof AuthenticatedMembreHistoriqueRoute
  AuthenticatedMembreLoggerRoute: typeof AuthenticatedMembreLoggerRoute
  AuthenticatedMembreMessagesRoute: typeof AuthenticatedMembreMessagesRoute
  AuthenticatedMembrePlanningRoute: typeof AuthenticatedMembrePlanningRoute
  AuthenticatedMembreProfilRoute: typeof AuthenticatedMembreProfilRoute
  AuthenticatedMembreProgrammeRoute: typeof AuthenticatedMembreProgrammeRoute
  AuthenticatedMembreProgressionRoute: typeof AuthenticatedMembreProgressionRoute
  AuthenticatedMembreIndexRoute: typeof AuthenticatedMembreIndexRoute
  AuthenticatedMembreSeanceLibreSessionIdRoute: typeof AuthenticatedMembreSeanceLibreSessionIdRoute
  AuthenticatedMembreSeanceSessionIdRoute: typeof AuthenticatedMembreSeanceSessionIdRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedCoachRoute: AuthenticatedCoachRouteWithChildren,
  AuthenticatedMembreCarnetRoute: AuthenticatedMembreCarnetRouteWithChildren,
  AuthenticatedMembreCommencerRoute: AuthenticatedMembreCommencerRoute,
  AuthenticatedMembreHistoriqueRoute: AuthenticatedMembreHistoriqueRoute,
  AuthenticatedMembreLoggerRoute: AuthenticatedMembreLoggerRoute,
  AuthenticatedMembreMessagesRoute: AuthenticatedMembreMessagesRoute,
  AuthenticatedMembrePlanningRoute: AuthenticatedMembrePlanningRoute,
  AuthenticatedMembreProfilRoute: AuthenticatedMembreProfilRoute,
  AuthenticatedMembreProgrammeRoute: AuthenticatedMembreProgrammeRoute,
  AuthenticatedMembreProgressionRoute: AuthenticatedMembreProgressionRoute,
  AuthenticatedMembreIndexRoute: AuthenticatedMembreIndexRoute,
  AuthenticatedMembreSeanceLibreSessionIdRoute:
    AuthenticatedMembreSeanceLibreSessionIdRoute,
  AuthenticatedMembreSeanceSessionIdRoute:
    AuthenticatedMembreSeanceSessionIdRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
  OnboardingStepRoute: OnboardingStepRoute,
  ApiPublicHooksGenerateLogbooksRoute: ApiPublicHooksGenerateLogbooksRoute,
  LovableEmailAuthPreviewRoute: LovableEmailAuthPreviewRoute,
  LovableEmailAuthWebhookRoute: LovableEmailAuthWebhookRoute,
  LovableEmailQueueProcessRoute: LovableEmailQueueProcessRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
